# Generated by Django 4.1.2 on 2022-10-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measuremen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sensor', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('date_measuremen', models.DateTimeField()),
                ('sensors', models.ManyToManyField(related_name='measuremen', to='measurement.sensor')),
            ],
        ),
    ]
