# Generated by Django 4.1.2 on 2022-11-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuremen',
            name='id_sensor',
        ),
        migrations.RemoveField(
            model_name='measuremen',
            name='sensors',
        ),
        migrations.AddField(
            model_name='measuremen',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measuremen', to='measurement.sensor'),
        ),
        migrations.AlterField(
            model_name='measuremen',
            name='date_measuremen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
