# Generated by Django 4.1.2 on 2022-11-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_measuremen_id_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuremen',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measuremen', to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
